app = "bidaktv-demo2-be"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[deploy]
  release_command = "npx prisma migrate deploy"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
